### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [diharaw/Lumen#2]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/116843845-d0100900-ac13-11eb-9c18-f8fccb87ac3b.png)

thank you  
best regards to you  
William

**Comment by diharaw** [comment]
Looks like you haven’t recursively cloned the repository and the sub modules haven’t been cloned. Please use this git command to clone the repository as mentioned in the build instructions:

`git clone --recursive https://github.com/diharaw/Helios.git `
